'use client';

import Providers from '@/components/providers';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Navbar';
import Toast from '@/components/Toast';
import {
  QueryClient,
  QueryClientProvider,
  QueryOptions,
} from '@tanstack/react-query';
import React from 'react';
import { axiosAuth } from '@/lib/axios';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const defaultQueryFn = async ({ queryKey }: QueryOptions) => {
  const res = await axiosAuth.get(`${queryKey?.[0]}`);
  return res.data;
};

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      queryFn: defaultQueryFn,
    },
  },
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <QueryClientProvider client={queryClient}>
          <Toast />
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </QueryClientProvider>
      </body>
    </html>
  );
}
